version: '3.8'

services:
    app:
        image: golang-postgresql-sql-builder-example
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - POSTGRES_URL=postgres://postgres:password@postgres:5432/blog?sslmode=disable
        depends_on:
            - postgres

    postgres:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: blog
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
