//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Posts = newPostsTable("public", "posts", "")

type postsTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnInteger
	UserID    postgres.ColumnInteger
	Title     postgres.ColumnString
	Content   postgres.ColumnString
	CreatedAt postgres.ColumnTimestamp
	UpdatedAt postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PostsTable struct {
	postsTable

	EXCLUDED postsTable
}

// AS creates new PostsTable with assigned alias
func (a PostsTable) AS(alias string) *PostsTable {
	return newPostsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PostsTable with assigned schema name
func (a PostsTable) FromSchema(schemaName string) *PostsTable {
	return newPostsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PostsTable with assigned table prefix
func (a PostsTable) WithPrefix(prefix string) *PostsTable {
	return newPostsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PostsTable with assigned table suffix
func (a PostsTable) WithSuffix(suffix string) *PostsTable {
	return newPostsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPostsTable(schemaName, tableName, alias string) *PostsTable {
	return &PostsTable{
		postsTable: newPostsTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newPostsTableImpl("", "excluded", ""),
	}
}

func newPostsTableImpl(schemaName, tableName, alias string) postsTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		UserIDColumn    = postgres.IntegerColumn("user_id")
		TitleColumn     = postgres.StringColumn("title")
		ContentColumn   = postgres.StringColumn("content")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		UpdatedAtColumn = postgres.TimestampColumn("updated_at")
		allColumns      = postgres.ColumnList{IDColumn, UserIDColumn, TitleColumn, ContentColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{UserIDColumn, TitleColumn, ContentColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return postsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		UserID:    UserIDColumn,
		Title:     TitleColumn,
		Content:   ContentColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
